"""Agent-visible tool schemas, handlers, and adapters for OpenETA."""

from agent.tools.registry import (
    TOOL_RESULT_SCHEMA_VERSION,
    ToolEffect,
    ToolExecutionContext,
    ToolHandler,
    ToolRegistry,
    ToolResult,
    ToolSpec,
    build_default_tool_registry,
    make_tool_result,
    make_tool_result_details,
    tool_result_type,
)
from agent.tools.handlers import (
    bind_dummy_tool_handlers,
    build_anygrasp_handler,
    build_anyplace_handler,
    build_contact_graspnet_handler,
    build_sam3_handler,
    build_sse_anygrasp_mcp_grasper,
    build_sse_anyplace_mcp_placer,
    build_sse_contact_graspnet_mcp_predictor,
    build_sse_sam3_mcp_segmenter,
    build_stdio_anyplace_mcp_placer,
    build_stdio_contact_graspnet_mcp_predictor,
)

__all__ = [
    "TOOL_RESULT_SCHEMA_VERSION",
    "ToolEffect",
    "ToolExecutionContext",
    "ToolHandler",
    "ToolRegistry",
    "ToolResult",
    "ToolSpec",
    "bind_dummy_tool_handlers",
    "build_anygrasp_handler",
    "build_anyplace_handler",
    "build_contact_graspnet_handler",
    "build_default_tool_registry",
    "build_sam3_handler",
    "build_sse_anygrasp_mcp_grasper",
    "build_sse_anyplace_mcp_placer",
    "build_sse_contact_graspnet_mcp_predictor",
    "build_sse_sam3_mcp_segmenter",
    "build_stdio_anyplace_mcp_placer",
    "build_stdio_contact_graspnet_mcp_predictor",
    "make_tool_result",
    "make_tool_result_details",
    "tool_result_type",
]
