"""Optional backends for generating bounded Code-as-Policy snippets."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field

from adapter.protocol import JsonDict
from agent.runtime.actions import PipelineStatus


@dataclass(slots=True)
class CodePolicyGenerationRequest:
    """Request sent to an agent backend for policy-code generation."""

    policy_context: JsonDict
    system_prompt: str = ""
    metadata: JsonDict = field(default_factory=dict)


@dataclass(slots=True)
class CodePolicyGenerationResult:
    """Result returned by a code-policy generation backend."""

    code: str
    status: PipelineStatus
    provider: str = "placeholder"
    model: str = "none"
    details: JsonDict = field(default_factory=dict)


class CodePolicyBackend(ABC):
    """Backend that turns policy context into executable control code.

    Real implementations may call commercial APIs, local models, or a Pi-style
    provider collection. They should not execute simulator code directly.
    """

    @abstractmethod
    def generate(self, request: CodePolicyGenerationRequest) -> CodePolicyGenerationResult:
        """Generate one bounded Code-as-Policy snippet."""

    def descriptor(self) -> JsonDict:
        return {
            "name": type(self).__name__,
            "implemented": not isinstance(self, PlaceholderCodePolicyBackend),
        }


class PlaceholderCodePolicyBackend(CodePolicyBackend):
    """Backend used until a real model/provider implementation is connected."""

    def generate(self, request: CodePolicyGenerationRequest) -> CodePolicyGenerationResult:
        task = repr(request.policy_context["task"])
        code = "\n".join(
            [
                "# OpenETA Code-as-Policy placeholder.",
                "# Replace this with code generated by the agent backend.",
                f"TASK = {task}",
                "RESULT = {",
                "    'status': 'pending_policy_generation',",
                "    'task': TASK,",
                "    'reason': 'No policy generation backend is connected yet.',",
                "}",
            ]
        )
        return CodePolicyGenerationResult(
            code=code,
            status=PipelineStatus.PENDING,
            details={"policy_context_keys": sorted(request.policy_context.keys())},
        )


@dataclass(slots=True)
class CommercialApiBackendConfig:
    """Configuration placeholder for an API-backed code-policy generator."""

    provider: str
    model: str
    api_base: str | None = None
    api_key_env: str | None = None
    timeout_s: float = 60.0
    metadata: JsonDict = field(default_factory=dict)


class CommercialApiCodePolicyBackend(CodePolicyBackend):
    """Shape of a future commercial-API backed policy generator.

    This intentionally has no network implementation yet. The Pi reference
    suggests keeping provider/model/auth resolution behind this boundary.
    """

    def __init__(self, config: CommercialApiBackendConfig) -> None:
        self.config = config

    def generate(self, request: CodePolicyGenerationRequest) -> CodePolicyGenerationResult:
        del request
        raise NotImplementedError(
            "Commercial API code-policy generation is not wired yet. "
            "Implement provider/model/auth handling behind CodePolicyBackend."
        )

    def descriptor(self) -> JsonDict:
        payload = super().descriptor()
        payload.update(
            {
                "provider": self.config.provider,
                "model": self.config.model,
                "api_base": self.config.api_base,
                "api_key_env": self.config.api_key_env,
            }
        )
        return payload
